# Generated by Django 5.2.4 on 2025-07-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/', verbose_name='Archivo Adjunto del Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólares Americanos (U$S)'), ('ARS', 'Pesos Argentinos (ARS$)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coste Inicial'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de YouTube del Proyecto'),
        ),
    ]
