# Generated by Django 5.2.4 on 2025-07-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='task',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL de YouTube'),
        ),
    ]
