# Generated by Django 5.2.4 on 2025-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designa si este cliente debe ser tratado como activo. Desmarcar en lugar de borrar.'),
        ),
    ]
